# Generated by Django 4.0.2 on 2022-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('universidad', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
