# Generated by Django 4.0.2 on 2022-03-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarSalida', models.CharField(max_length=200)),
                ('lugarLlegada', models.CharField(max_length=200)),
                ('ruta', models.CharField(max_length=200)),
                ('fechaSalida', models.DateTimeField()),
            ],
        ),
    ]
