# Generated by Django 3.2.8 on 2022-03-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horario',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
