# Generated by Django 3.2.8 on 2022-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='horario',
            field=models.ImageField(blank=True, default='horarios/default.png', upload_to='horarios'),
        ),
    ]
