# Generated by Django 3.2.8 on 2022-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
