# Generated by Django 3.2.8 on 2022-05-04 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
